# Site settings
name: Harper He
title: Harper He | Market Intelligence Analyst
description: Business Analyst with marketing expertise, research skills, analytical thinking, business acumen, and computer proficiency
url: https://harper-he.github.io/
baseurl: ''
email: harperhe07@gmail.com
cover: https://harper-he.github.io/img/cover.png
logo: https://harper-he.github.io/img/emojis/technologist.png
resume: https://harper-he.github.io/resume.pdf
social:
  - title: email
    url: mailto:harperhe07@gmail.com
  - title: github
    url: https://github.com/harper-he
  - title: linkedin
    url: https://www.linkedin.com/in/harper-he

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
